// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfqwiwdjjflzezzrxqbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmcXdpd2RqamZsemV6enJ4cWJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0Nzg1NDksImV4cCI6MjA3NDA1NDU0OX0.aaoL6sQkSSFDakdLwU_-3eMjP9Vfiu0HjrQY-GQqMZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});